// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v5.26.1
// source: accountFlow.proto

package accountFlow

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccountFlow struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId  int64 `protobuf:"varint,1,opt,name=AccountId,json=account_id,proto3" json:"AccountId,omitempty"`
	UploadFlow int64 `protobuf:"varint,2,opt,name=UploadFlow,json=upload_flow,proto3" json:"UploadFlow,omitempty"`
}

func (x *AccountFlow) Reset() {
	*x = AccountFlow{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accountFlow_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountFlow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountFlow) ProtoMessage() {}

func (x *AccountFlow) ProtoReflect() protoreflect.Message {
	mi := &file_accountFlow_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountFlow.ProtoReflect.Descriptor instead.
func (*AccountFlow) Descriptor() ([]byte, []int) {
	return file_accountFlow_proto_rawDescGZIP(), []int{0}
}

func (x *AccountFlow) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *AccountFlow) GetUploadFlow() int64 {
	if x != nil {
		return x.UploadFlow
	}
	return 0
}

type AccountFlows struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountFlowDatas []*AccountFlow `protobuf:"bytes,1,rep,name=AccountFlowDatas,proto3" json:"AccountFlowDatas,omitempty"`
}

func (x *AccountFlows) Reset() {
	*x = AccountFlows{}
	if protoimpl.UnsafeEnabled {
		mi := &file_accountFlow_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccountFlows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountFlows) ProtoMessage() {}

func (x *AccountFlows) ProtoReflect() protoreflect.Message {
	mi := &file_accountFlow_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountFlows.ProtoReflect.Descriptor instead.
func (*AccountFlows) Descriptor() ([]byte, []int) {
	return file_accountFlow_proto_rawDescGZIP(), []int{1}
}

func (x *AccountFlows) GetAccountFlowDatas() []*AccountFlow {
	if x != nil {
		return x.AccountFlowDatas
	}
	return nil
}

var File_accountFlow_proto protoreflect.FileDescriptor

var file_accountFlow_proto_rawDesc = []byte{
	0x0a, 0x11, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77,
	0x22, 0x4d, 0x0a, 0x0b, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x12,
	0x1d, 0x0a, 0x09, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x12, 0x1f,
	0x0a, 0x0a, 0x55, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x46, 0x6c, 0x6f, 0x77, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0b, 0x75, 0x70, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x66, 0x6c, 0x6f, 0x77, 0x22,
	0x54, 0x0a, 0x0c, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x73, 0x12,
	0x44, 0x0a, 0x10, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x44, 0x61,
	0x74, 0x61, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x63, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x46,
	0x6c, 0x6f, 0x77, 0x52, 0x10, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77,
	0x44, 0x61, 0x74, 0x61, 0x73, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x61, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x46, 0x6c, 0x6f, 0x77, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_accountFlow_proto_rawDescOnce sync.Once
	file_accountFlow_proto_rawDescData = file_accountFlow_proto_rawDesc
)

func file_accountFlow_proto_rawDescGZIP() []byte {
	file_accountFlow_proto_rawDescOnce.Do(func() {
		file_accountFlow_proto_rawDescData = protoimpl.X.CompressGZIP(file_accountFlow_proto_rawDescData)
	})
	return file_accountFlow_proto_rawDescData
}

var file_accountFlow_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_accountFlow_proto_goTypes = []interface{}{
	(*AccountFlow)(nil),  // 0: accountFlow.AccountFlow
	(*AccountFlows)(nil), // 1: accountFlow.AccountFlows
}
var file_accountFlow_proto_depIdxs = []int32{
	0, // 0: accountFlow.AccountFlows.AccountFlowDatas:type_name -> accountFlow.AccountFlow
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_accountFlow_proto_init() }
func file_accountFlow_proto_init() {
	if File_accountFlow_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_accountFlow_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountFlow); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_accountFlow_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccountFlows); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_accountFlow_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_accountFlow_proto_goTypes,
		DependencyIndexes: file_accountFlow_proto_depIdxs,
		MessageInfos:      file_accountFlow_proto_msgTypes,
	}.Build()
	File_accountFlow_proto = out.File
	file_accountFlow_proto_rawDesc = nil
	file_accountFlow_proto_goTypes = nil
	file_accountFlow_proto_depIdxs = nil
}
