name: 自动打包为镜像并推送DockerHub仓库[TOC-AGENT-ADMIN服务]

on:
  push:
    tags:
      - 'toc-agent-admin-v*' 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v4

      - name: 设置Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 登录到DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: 解析标签为编译参数和构建并推送Docker镜像
        id: extract_tag
        run: |
          FULL_TAG=${GITHUB_REF#refs/tags/}
          TAG=${FULL_TAG#toc-agent-admin-v}
          IFS='-' read -r VERSION TARGETOS TARGETARCH <<< "$TAG"
          echo "Parsed tag: $VERSION, target OS: $TARGETOS, target arch: $TARGETARCH"
          if [ -z "$VERSION" ] || [ -z "$TARGETOS" ] || [ -z "$TARGETARCH" ]; then
            echo "Error: One of the required variables is empty."
            exit 1
          fi
          docker build -f Dockerfile -t toc-agent-admin . --build-arg BUILDDIR=./cmd/api --build-arg EXPOSE_PORT=8098 --build-arg TARGETOS=$TARGETOS --build-arg TARGETARCH=$TARGETARCH
          TAG_NAME="dahangkk/toc-agent-admin:${VERSION}_${TARGETARCH}"
          echo "Tagging image as $TAG_NAME"
          docker tag toc-agent-admin:latest $TAG_NAME
          echo "Pushing image $TAG_NAME"
          docker push $TAG_NAME
